# Generated by Django 3.2 on 2023-01-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set(),
        ),
    ]
