# Generated by Django 3.2 on 2023-01-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_author_telegram_chat_id'),
        ('posts', '0002_alter_status_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('post', 'author')},
        ),
    ]
